setup: |
  echo "🐊 Attempt to install exposition engineering tools"
  echo "🐊 Using pipx to perform program installation"
  echo "🐊 Will not re-install if already installed"
  pipx install pymarkdownlnt
---

# Checks on Files {{{

# perform checks on a file
- writing/outlines/show_outline_one.md:
    - description: Ensure that the show_outline_one.md file exists in the writing/outlines/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for the outline
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the outline file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Retype the every word in the Honor Code pledge in outline.md
      check: MatchFileFragment
      options:
        fragment: "I adhered to the Allegheny College Honor Code while completing this project."
        count: 3
        exact: true
    - description: Confirm that the markdown file containing the show outline has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 18
        exact: false
    - description: Confirm that the markdown file containing the show outline has the correct number of lists
      check: CountMarkdownTags
      options:
        tag: list
        count: 7
        exact: false
    - description: Confirm that the markdown file containing the show outline has a minimum number of paragraphs
      check: CountMarkdownTags
      options:
        tag: paragraph
        count: 3
        exact: false
    - description: Confirm that the markdown file containing the show outline has the correct number of links
      check: CountMarkdownTags
      options:
        tag: link
        count: 17
        exact: false
    - description: Confirm that the markdown file containing the show outline has the HTML block markers
      check: CountMarkdownTags
      options:
        tag: html_block
        count: 2
        exact: true
    - description: Confirm that the markdown file containing the show outline has a show detail keyword
      check: MatchFileFragment
      options:
        fragment: "**Title**:"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the show outline has a show detail keyword
      check: MatchFileFragment
      options:
        fragment: "**Host**:"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the show outline has a show detail keyword
      check: MatchFileFragment
      options:
        fragment: "**Guest**:"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the show outline has the objective labels
      check: MatchFileFragment
      options:
        fragment: "**Objective"
        count: 3
        exact: true
    - description: Confirm that the markdown file containing the show outline has the question labels
      check: MatchFileFragment
      options:
        fragment: "**Question"
        count: 3
        exact: false
    - description: Delete the 'Sub-Section One' prompt in the outline file
      check: MatchFileFragment
      options:
        fragment: "Sub-Section One"
        count: 0
        exact: true
    - description: Delete the 'Sub-Section Two' prompt in the outline file
      check: MatchFileFragment
      options:
        fragment: "Sub-Section Two"
        count: 0
        exact: true
    - description: Delete the 'Sub-Section Three' prompt in the outline file
      check: MatchFileFragment
      options:
        fragment: "Sub-Section Three"
        count: 0
        exact: true
    - description: Confirm that the markdown file containing the show outline has the references
      check: MatchFileFragment
      options:
        fragment: "**Reference"
        count: 3
        exact: true

# perform checks on a file
- writing/examples/Hyrum-Wright-On-Software-Engineering-At-Google.md:
    - description: Ensure that the an example outline file exists in the writing/examples/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for an example file
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- writing/examples/Sebastian-Ramirez-On-FastAPI.md:
    - description: Ensure that the an example outline file exists in the writing/examples/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for an example file
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# perform checks on a file
- writing/examples/Wolf-Vollprecht-on-Rust-Based-Tooling-for-Python.md:
    - description: Ensure that the an example outline file exists in the writing/examples/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for an example file
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

# }}}

# Check Output from Linters {{{

# run a check
- description: Confirm that the show outline files passes the linting checks run by pymarkdownlnt
  command: "pymarkdown --config .pymarkdown.cfg scan writing/outlines/show_outline_one.md"

# }}}

# Commits {{{

# count number of commits in the GitHub repository
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 10

# }}}
